"""Initial migration.

Revision ID: 8013b3ea6cc9
Revises: 
Create Date: 2026-01-17 14:13:02.563543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8013b3ea6cc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
